### ISSUE TITLE
界面传递参数可以支持onActivityResult结果获取吗

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Serialize#11]
目前使用官方新推出的api感觉使用起来有点麻烦😂我想要是能用你提供的界面传递参数跳转Activity的写法，在后面加个大括号，用lambda表达式的写法获取到返回的数据执行后续操作就好了🤔

**Comment by liangjingkanji** [comment]
你说的是onActivityResult Api吧?  resultful 是网络请求

**Comment by SaltedFish-Extreme** [comment]
> 你说的是onActivityResult Api吧? resultful 是网络请求

嗯，是onActivityResult API😂

**Comment by liangjingkanji** [comment]
属实丢人

**Comment by liangjingkanji** [comment]
暂时没空, 但是可以考虑

欢迎你的pr

**Comment by SaltedFish-Extreme** [comment]
好的😂我也是刚才看一个老哥封装的[onActivityResult框架](https://github.com/iDeMonnnnnn/DeMon-ARA/blob/main/core-ktx/src/main/java/com/demon/corektx/ActivityResultApi.kt)才想起来的，我等用用看看，看看能不能在你的上面改改🤔

**Comment by liangjingkanji** [comment]
我之前就有过这方面想法, 后来处理别的忘了

大家一起努力减少重复工作增加摸鱼时间

**Comment by SaltedFish-Extreme** [comment]
好的😄
