### ISSUE TITLE
集合无法保存数据

### ISSUE THREAD

**Issue by fengtech** [liangjingkanji/Serialize#12]
@Parcelize
data class MtbAStdTFEntity(
    var CurrentMax: Double = 0.0,
    var CurrentMin: Double = 0.0,
    var Duration: Int = 0,
    var Freq: Int = 0,
    var item: Int = 0
) : Parcelable

object MtbaSet {
var listStdTF   : MutableList<MtbAStdTFEntity>  by serialLazy()
}

通过对listStdTF赋值后发现只是内存中数据改，没有保存到磁盘，app重启启动时候没有数据，是否用法有问题

**Comment by liangjingkanji** [comment]
你是不是往集合里面添加元素, 然后发现元素没有保存到磁盘

因为只能保存对象, 对于对象自身的属性变动无法识别也无法保存

**Comment by liangjingkanji** [comment]
我的回复中包含文档提及

**Comment by fengtech** [comment]
看了文档， 实际上我就是用 serialLazy() , 没有效果
 var listStdTF : MutableList by serialLazy()

**Comment by liangjingkanji** [comment]
文档写错了, `serialLazy()`也不会触发保存, 保存和`liveData`一样只能处理value而不能监听value里面的字段

**Comment by liangjingkanji** [comment]
关于列表建议使用数据库保存, 因为存在N多条元素, 可能会在集合体积非常大的情况下影响高度读写性能

**Comment by fengtech** [comment]
明白了， 主要是一些不确定数量但是数据又不多的列表我想通过这种方式保存。

**Comment by liangjingkanji** [comment]
我当初设计也是为了保存这些轻量级数据方便主线程读写

我将会更新完善文档, 如果你发现错误也可以修改后发起pr
