### ISSUE TITLE
每次更新存储，在mmkv.default文件都会多一条数据，还是部分乱码

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Serialize#15]
这个正常吗？是日志还是保存的数据？

<img width="337" alt="微信图片_20220627160719" src="https://user-images.githubusercontent.com/54784104/175891645-b8ef8f6c-bc94-4d5c-a647-f7d640ef7b5f.png">

**Comment by SaltedFish-Extreme** [comment]
只有更新才会多，查询读取不会多

**Comment by liangjingkanji** [comment]
这是MMKV框架生成的, 具体你看下MMKV项目说明

**Comment by SaltedFish-Extreme** [comment]
好吧😂

**Comment by liangjingkanji** [comment]
我比较忙没空回答其他框架的问题, 而且我也不够熟悉

**Comment by SaltedFish-Extreme** [comment]
好吧😥
