### ISSUE TITLE
期望全局可配置 MMKV 的 mode 和 cryptKey

### ISSUE THREAD

**Issue by nEdAy** [liangjingkanji/Serialize#16]
defaultMMKV(int mode, @Nullable String cryptKey)

**Comment by liangjingkanji** [comment]
mmkv本身就支持全局配置

**Comment by nEdAy** [comment]
@liangjingkanji 没找到 API 呀，目前看只能对某个 by serial() 设置它使用的 kv
我的需求是 可针对一个类下 所有  by serial() 等字段 配置它使用的 kv（业务字段、加密密钥）这样

类似这样写？
https://github.com/liangjingkanji/Serialize/commit/efc9b6afc9f3d043b9150a390b069ddd09834b8b

**Comment by liangjingkanji** [comment]
那这是不支持的

**Comment by liangjingkanji** [comment]
已经计划提供Hook接口回调来配置加密/解密数据了
并且计划使用kotlin-serialization来序列化/反序列化来解决Parcelable/Serializable增删字段导致的一系列问题

**Comment by liangjingkanji** [comment]
2.0.0版本已经只是实现`SerializeHook`接口自定义序列化实现, 可以进行加密解密

**Comment by liangjingkanji** [comment]
现在支持全局配置mmkv

```kotlin
Serialize.mmkv = MMKV.defaultMMKV()
```

单例配置

```kotlin
@SerializeConfig(mmapID = "app_config") // 指定mmapID可以避免重命名当前类名或者改变包名导致无法读取旧值
object AppConfig {
    var userId: String by serialLazy(name="user_id") // 指定name可以避免重命名当前字段导致无法读取旧值
}
```

**Comment by nEdAy** [comment]
> 现在支持全局配置mmkv
> 
> ```kotlin
> Serialize.mmkv = MMKV.defaultMMKV()
> ```
> 
> 单例配置
> 
> ```kotlin
> @SerializeConfig(mmapID = "app_config") // 指定mmapID可以避免重命名当前类名或者改变包名导致无法读取旧值
> object AppConfig {
>     var userId: String by serialLazy(name="user_id") // 指定name可以避免重命名当前字段导致无法读取旧值
> }
> ```

这应该是我需要的，感谢东哥
