### ISSUE TITLE
支持 Preference 渐进迁移么？

### ISSUE THREAD

**Issue by mcxinyu** [liangjingkanji/Serialize#20]
你好，应用中原来已经使用了 Preferences 存储了一些字段，能怎样迁移过来呢？

**Comment by mcxinyu** [comment]
提交了一种可能的方式，麻烦大佬给些意见。

**Comment by liangjingkanji** [comment]
1. MMKV支持sp迁移
2. `2.0.0`版本提供实现`SerializeHook`接口自定义序列化实现, 可以借此来渐进式迁移
