### ISSUE TITLE
我直接写在kotlin file里面好像不行，一定要加上类名吗？

### ISSUE THREAD

**Issue by rayzeng0221** [liangjingkanji/Serialize#22]
我是想调用的时候方便点不用再用类名调用，但是不加类名好像 by serilizer()就会报错

**Comment by liangjingkanji** [comment]
是的吧不过我也没试过, 我建议不要定义这种顶层变量(避免污染命名空间), 建议在`object`单例类中使用

**Comment by liangjingkanji** [comment]
直接使用`serialize()/deserialize()`不就行了
