### ISSUE TITLE
重启应用后，保存的对象为空了

### ISSUE THREAD

**Issue by rayzeng0221** [liangjingkanji/Serialize#23]
我的项目正在使用 kotlinx.serialization，有这样一个类：
`@Serializable
data class LoginDto(
    @SerialName("accountId")
    val accountId: String?,
    @SerialName("address")
    val address: String?,
    @SerialName("appRole")
    val appRole: String?
)`
这应该就是算序列化了吧？  但是保存之后当时有效，但是当我退出应该重新进入APP，这时候对象就是获取为空了。

**Comment by liangjingkanji** [comment]
`@Serializable`是kotlinx.serialization的注解, 和本框架没关系

> 本框架目前正在计划支持ks序列化, 以摆脱Serializable/Parcelable局限性

**Comment by liangjingkanji** [comment]
Duplicate of #14

**Comment by liangjingkanji** [comment]
改变对象内的字段并不会自动更新本地序列化数据, 你需要重新赋值触发保存, 参考[文档](https://liangjingkanji.github.io/Serialize/#_12)
