### ISSUE TITLE
框架版本更新问题

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Serialize#27]
请问新版的browse和share函数没了吗？

**Comment by liangjingkanji** [comment]
职责不明确，所以删除了，大版本更新存在api变动

**Comment by SaltedFish-Extreme** [comment]
好吧，我项目里有用这个的地方，那还是找替换的方法吧😂

**Comment by liangjingkanji** [comment]
这两个功能很简单，最开始考虑大家一起贡献intent,  但是考虑到始终没人贡献我认为精力有限精简框架职责更好，用的人多我考虑的侧重点也会发生变化

**Comment by SaltedFish-Extreme** [comment]
👌
