### ISSUE TITLE
使用动态键名的默认值并没有进行隔离？

### ISSUE THREAD

**Issue by rayzeng0221** [liangjingkanji/Serialize#28]
```kotlin
var sceneMusic: Boolean by serialLazy(true, name = "scene_music_${globalMac.toMac()}_${userInfoId}")
```
当我第一次改变他的值为false       接着  我改变 动态键名的  变量的值，这时候再去读取值，动态键名变量已经改了，这时候读取的不应该是默认值true吗？但是读取出来的 还是  上一个动态键名的 值   false

**Comment by rayzeng0221** [comment]
`var globalMac = ""
    var userInfoId = ""

    var sceneMusic: Boolean by serialLazy(true, name = "scene_music_${globalMac}_${userInfoId}")`


` // 写入
            binding.cardWriteField -> {
               // name = "https://github.com/liangjingkanji/Serialize"
                //toast("写入数据: $name 到磁盘")
                globalMac = "C300000030A1"
                userInfoId = "1647308209"
                sceneMusic = false
                Log.i("zy1997", "onClick: 写入之后的值是---${sceneMusic}")
            }`


` // 读取
            binding.cardReadField -> {
                //toast("读取本地数据为: $name")
                globalMac = "CE3431345450"
                //userInfoId = "1647308209"
                //sceneMusic = false
                Log.i("zy1997", "onClick: 写入之后的值是---${sceneMusic}")
            }`

**Comment by rayzeng0221** [comment]
上面这段代码  是我 直接在你的Demo里面复现  的   也是一样

**Comment by rayzeng0221** [comment]
<img width="1180" alt="截屏2023-03-08 15 36 04" src="https://user-images.githubusercontent.com/16337418/223650506-a9d885e3-74d1-4d96-88ca-7c79b5b55e96.png">
我现在暂时把它改成这样手机读写就是正常的，但是这样，我所有的 都得改，成本太大了，那我上面那个写法 要怎么才可以正常呀？

**Comment by liangjingkanji** [comment]
原因: `serialLazy`对值进行缓存了

1. 我猜测你可能想隔绝某个类的所有字段, 实际上本框架现在支持`Serialize.hook`拦截配置和序列化, [示例文档](https://liangjingkanji.github.io/Serialize/#_10)
2. 关于`by serialLazy`默认值没有隔绝的问题你可以暂时换成`by serial`来解决, 其并不会缓存数据, 该问题我近期进行修复(工作繁忙)

建议迁移使用自定义序列化来存储数据, 因为默认`Serialize/Parcelable`等方式无法很好的兼容字段变更

**Comment by rayzeng0221** [comment]
没用哦，早上已经试过了，都是一样的 。
`var sceneMusic: Boolean by serial(true, name = "scene_music_${globalMac}_${userInfoId}")`

**Comment by liangjingkanji** [comment]
使用的最新版本吗？

**Comment by rayzeng0221** [comment]
> 使用的最新版本吗？

是啊，而且我还是直接在你的 Demo里面改的

**Comment by liangjingkanji** [comment]
这是语法问题并不能解决, 除非将`name`改为函数回调

**函数参数仅会调用一次**

**Comment by rayzeng0221** [comment]
> 1. **函数参数仅会调用一次**, 这是语法问题框架并不能解决, 除非将`name`改为函数回调
> 2. 更新至最新版本将支持`{}`函数回调设置`name`: [动态键名](https://liangjingkanji.github.io/Serialize/#_11)
>    ```kotlin
>    private var balance: String by serial("0.0", { "balance-$userId" })
>    ```
> 3. 推荐使用`Serialize.hook`实现拦截动态配置mmapId隔离数据, [示例文档](https://liangjingkanji.github.io/Serialize/#_10)

嗯嗯，试了最新版本的 动态键名  确实已经可以啦。感谢大佬
