### ISSUE TITLE
取值的时候崩溃，有没有人遇到过

### ISSUE THREAD

**Issue by lee-you** [liangjingkanji/Serialize#34]
![image](https://github.com/liangjingkanji/Serialize/assets/18346188/ac6de1be-6d50-46d5-b338-7c0989a2cd77)
![image](https://github.com/liangjingkanji/Serialize/assets/18346188/3102c6d6-1197-4b26-a743-7f9b60385b35)

**Comment by liangjingkanji** [comment]
你可以搜下这个错误信息，这不是本框架抛出的

请复制贴出来

**Comment by liangjingkanji** [comment]
长时间未回复本问题关闭

建议你自定义一个SerializeHook使用吧, 文档有提到默认的Serializable序列化方式很危险
