### ISSUE TITLE
ProtoBuf序列化一个有null的对象好像会报错啊

### ISSUE THREAD

**Issue by BugFactory9527** [liangjingkanji/Serialize#37]
<img width="313" alt="image" src="https://github.com/liangjingkanji/Serialize/assets/37281286/8f671b99-4958-4c2c-a111-0aafb1194df0">
0-0  用json就没问题

**Comment by liangjingkanji** [comment]
ks框架问题，和本项目无关

**Comment by BugFactoty** [comment]
data 数据类默认值会失效 改成普通class也不行。。 最后换成hook改成json了

**Comment by liangjingkanji** [comment]
默认值需要启用一个属性

**Comment by liangjingkanji** [comment]
```kotlin
val pb = ProtoBuf {
    encodeDefaults = true
}
```
