### ISSUE TITLE
这是为啥

### ISSUE THREAD

**Issue by zs1973** [liangjingkanji/Serialize#38]
![image](https://github.com/liangjingkanji/Serialize/assets/8916333/765431e5-228f-4636-93b0-0faf4e830039)
avatar可以，nickname就不可以了

**Comment by liangjingkanji** [comment]
鼠标移上去，看错误提示

**Comment by liangjingkanji** [comment]
因为serialLiveData要求声明为val类型不可变变量吧

**Comment by liangjingkanji** [comment]
没有特殊需求不建议全部声明成`MutableLiveData`, 增加代码复杂度
