### ISSUE TITLE
老哥，我刚才预览自定义视图时候有个初始化MMKV的异常信息，这个需要弄吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Serialize#9]
![image](https://user-images.githubusercontent.com/54784104/153357182-871ecc5f-d79d-4003-8cd7-662a97c23aaf.png)

**Comment by liangjingkanji** [comment]
估计是你使用了多进程，那mmkv需要在application的onCreate手动调用`MMKV.initialize`

**Comment by liangjingkanji** [comment]
CententProvide自动初始化在多进程配置无效

**Comment by SaltedFish-Extreme** [comment]
我也不清楚😂我还不知道怎么用多进程，但是这个只在这个预览视图里显示了，代码跑也没问题，刚才在application里配置了初始化也还是提示这个，不管了😂
